{% set name = "voila-gridstack" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b28b3060fbf027e9842b5fc77697c08c78f1a2aefdca5b27de7af4bed0a99a12

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - voila >=0.2.0,<0.3

test:
  commands:
    - test -f "${PREFIX}/share/jupyter/nbconvert/templates/gridstack/index.html.j2"

about:
  home: https://github.com/voila-dashboards/voila-gridstack
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Gridstack template for Voilà'

extra:
  recipe-maintainers:
    - scopatz
    - SylvainCorlay
    - maartenbreddels
    - jtpio
