{% set name = "voila-gridstack" %}
{% set version = "0.1.0rc0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c5eedba8236ee6871fcf64a5a931d095cd5eda156930bb7bfccac374c4589dac

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - voila >=0.2.0,<0.3

test:
  commands:
    - test -f "${PREFIX}/share/jupyter/nbconvert/templates/gridstack/index.html.j2"
    - test -f "${PREFIX}/share/jupyter/labextensions/@voila-dashboards/jupyterlab-gridstack/package.json"

about:
  home: https://github.com/voila-dashboards/voila-gridstack
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Gridstack template for Voilà

extra:
  recipe-maintainers:
    - scopatz
    - SylvainCorlay
    - maartenbreddels
    - jtpio
